spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:~/ecommerce
    data-username: sa
    data-password:
    driver-class-name: org.h2.Driver

security:
  require-ssl: true

server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.jks
    key-store-password: clp123
    key-alias: tomcat